# This is a direct definition of worker graphs and their assignment to workers.
# This is NOT the final design; it's just a placeholder until we have a more
# detailed discussion about configs and worker graphs and colocation/disaggregation.

model: "dummy"
eos_token_id: 2

node_groups:
  - node_names:
      - text_emb
      - concat_text
    ranks:
      - 0
  
  - node_names:
      - image_emb
      - concat_img
    ranks:
      - 0
  
  - node_names:
      - LLM
    ranks:
      - 1
    graph_walks:
      - prefill
  
  - node_names:
      - LLM
      - flow
    ranks:
      - 2
      - 3
    graph_walks:
      - decode
      - image_gen
  
  - node_names:
      - VAE_dec
    ranks:
      - 4
