node_groups:
  - node_names:
      - ThinkerLLM
    ranks:
      - 0
    graph_walks:
      - prefill

  - node_names:
      - ThinkerLLM
    ranks:
      - 1
    graph_walks:
      - decode

  - node_names:
      - TalkerLLM
      - MTP
    ranks:
      - 2

  - node_names:
      - AudioCodec
    ranks:
      - 3
