model: "qwen3_omni"
max_seq_len: 32768
node_groups:
  - node_names: [audio_encoder, vision_encoder, Code2Wav]
    ranks: [0]
  
  - node_names: [Thinker]
    ranks: [0]
    graph_walks: [prefill_text, prefill_audio, prefill_vision]

  - node_names: [Thinker]
    ranks: [1]
    graph_walks: [thinker_decode]
  
  - node_names: [Talker_LLM, code_predictor]
    ranks: [2]