model: "qwen3_omni"
max_seq_len: 32768
node_groups:
  - node_names: [Thinker]
    ranks: [0, 1]
    tp_size: 2
  
  - node_names: [audio_encoder, vision_encoder]
    ranks: [0]

  - node_names: [Talker]
    ranks: [2]
  
  - node_names: [Code2Wav]
    ranks: [2]
